### ISSUE TITLE
2024.10.04 코드 리뷰

### ISSUE THREAD

**Issue by katanazero86** [mynolog/mynogram#1]
# 코드 리뷰

1. 프로젝트 구조   
components, hooks, pages, routes, service, store, utils 등의 폴더가 역할 또는 유형별로 분리되어 관리 및 유지보수를 하기 쉽게 잘 구성하였습니다.

2. 비동기 데이터 fetch 시, loading 또는 spinner 와 같은 UI를 제공하여 데이터가 불러와 지는지 직관적으로 알려주면 좋을거 같습니다.

3. /my-page 에서 새로고침 하면 404 에러가 발생합니다.

4. 만들기를 통해서 Mynogram 에 게시물을 등록하려고 할 때, 공유하기를 여러번 클릭하면 여러번 요청이 발생합니다. 공유하기를 클릭하면 요청이 완료되기전까지 disabled 처리를 하여 사용자가 실수로 2번 3번 클릭하여 요청이 2~3번 가지 않도록 하는게 좋습니다.

5. 프로필 수정이 동작을 하지 않는것으로 확인이 됩니다.(이미지까지 변경해야 수정이 되네요. 만약 내용만 수정을 한다면?)

6. zustand 를 활용한 인증 상태관리 패턴을 잘 적용하셨고, 상태 관리의 역할을 명확하게 분리하여 이를 컴포넌트와 명확히 연결하여 사용하면 유지보수에 유리해집니다.

7. types  폴더에서 각 도메인별 타입을 잘 구분하셨스니다. 그런데, 파일명이 파스칼 케이스로 시작하는게 있네요.   
소문자로 통일해주시면 좋겠습니다. 이를 통일하는 이유는 각 운영체제 파일 시스템에서 인식하는게 다르기 때문입니다. window 와 MacOS 는 대소문자를 구분하지는 않습니다. 하지만 리눅스에서는 철저히 대소문자를 구분합니다. 프로젝트를 개발하면 어떤 팀원은 윈도우, 어떤 팀원은 리눅스인데 대소문자를 구분하지 않는다면 경로 및 불러오는 파일명에서 오류가 발생할 수 있습니다. 이러한 오류는 협업 시 혼란을 초래하므로 일관된 파일명 표기법을 사용하세요!

8. 커스텀 훅을 사용하여 로직을 캡슐화하면 비지니스 로직과 UI 로직을 분리하므로 유지보수와 가독성이 좋아집니다.

현재 코드에서는 서비스 로직 호출 부분을 커스텀 훅 형태로 작성하면 역할이 명확해 질 것 같습니다.

9. env 를 사용하여 환경 변수값을 코드에서 분리하신것은 잘 하셨습니다. 

10. nav/icons.tsx 는 컴포넌트이기 때문에, nav/NavIcons.tsx 로 이름을 변경하는게 더 명확할 것 같습니다.   
NavItem 컴포넌트에 NavIcon 정보를 담은 객체로 대체하셔도 좋을것 같습니다.   
iconId 라는 props 를 내려받아 사용하고 있는데, 이거도 map() 형태로 렌더링 되도록 객체 배열을 가지고 있으면 코드가 좀 더 간결해지고 관리하기 쉬워집니다.

11. useForm 커스텀 훅은 제네릭 타입 받아서, 다양한 form 타입에 대응하도록 하신게 마음에 듭니다 :)

12. 현재 서버에서 받아오는 데이터는 zustand 를 통해서 관리하는것으로 파악이 됩니다. 현재는 작은 애플리케이션이기 때문에 문제가 되지는 않습니다만, 애플리케이션이 커지고 모든 서버 상태를 zustand 로 관리하려고 하면 서버 상태를 그때그때 동기화를 해줘야하고 정합성을 보장해줘야합니다. 또한, 캐싱 및 로직도 직접 구현하여 핸들링해야합니다.(옛날에는 서버에서 불러온 데이터를 store 에다가 넣어서 사용하는 흐름은 자연스러웠습니다만..) 그래서, 서버 상태 관리는 React Query, SWR 을 사용하시고, zustand 는 로컬 상태 및 UI 상태를 관리하는데 주력하면 더 역할도 명확해지고 효율적일 것 같습니다.(서버 상태와 클라이언트 상태를 구분하여 접근하자!)

### 고생했고, 컴포넌트 구조하는것도 최대한 분해하시는걸 연습하시는게 보여서 좋았습니다. 그런데, 꼭 작은 단위로 분해해야 좋은 컴포넌트는 아닙니다. 재사용성과 캡슐화가 잘 이루어져있는지 그리고 명확한 역할과 구조를 가지고 있는지 고민해보시면 좋겠습니다. 그리고 이름은 명확하게, CommonHr 보다는 보통 Divider 라고 합니다 :) (참조: https://mui.com/material-ui/react-divider/)

**Comment by mynolog** [comment]
이틀 정도 불태웠네요. 

3. firebase.json에서 rewrites 옵션으로 index.html로 리다이렉트 되도록 수정하였습니다.
7. 카멜케이스로 네이밍 컨벤션 통일하였습니다.
10. Icon.tsx -> NavIcon.tsx로 네이밍 컨벤션 통일하였습니다.

나머지 부분도 피드백 내용 바탕으로 더 나은 사용자 경험이 될 수 있도록 전체적으로 개선해보겠습니다.
코드리뷰 감사합니다!
